[build]
  command = "npm run build"
  publish = "./.next"
  environment = [
    "MINTER_PRIVATE_KEY",
    "TOKEN_CONTRACT_ADDRESS",
    "RPC_URL"
  ]

[[redirects]]
  from = "/*"
  to = "/"
  status = 200