[build]
  command = "npm run build"
  publish = "./.next"
  environment = { SECRETS_SCAN_ENABLED = "true" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200